export const SPECTORA_COLUMNS = {
  SECTION_NAME: 'Section Name',
  ITEM_NAME: 'Item Name',
  COMMENT_NAME: 'Comment Name',
  COMMENT_TEXT: 'Comment Text',
  COMMENT_TYPE: 'Comment Type',
  CATEGORY: 'Category',
  MULTIPLE_CHOICE_OPTIONS: 'Multiple Choice Options',
  UNIT_TYPE_OPTIONS: 'Unit Type Options',
  RECOMMENDATION: 'Recommendation',
  ORDER: 'Order',
  ANSWER_TYPE: 'Answer Type',
  DEFAULT_VALUE: 'Default Value',
  DEFAULT_VALUE_2: 'Default Value 2',
  DEFAULT_UNIT_TYPE: 'Default Unit Type',
  DEFAULT_LOCATION: 'Default Location',
  DEFAULT_ESTIMATE_MIN: 'Default Estimate Min',
  DEFAULT_ESTIMATE_MAX: 'Default Estimate Max',
  LOCKED: 'Locked',
  SIMPLE_FORMAT: 'Simple Format',
  DISABLE_PHOTOS: 'Disable Photos',
  USES: 'Uses',
  DEFAULT_PHOTO_1: 'Default Photo 1',
  DEFAULT_PHOTO_1_CAPTION: 'Default Photo 1 Caption',
  DEFAULT_PHOTO_2: 'Default Photo 2',
  DEFAULT_PHOTO_2_CAPTION: 'Default Photo 2 Caption',
  DEFAULT_PHOTO_3: 'Default Photo 3',
  DEFAULT_PHOTO_3_CAPTION: 'Default Photo 3 Caption',
  DEFAULT_PHOTO_4: 'Default Photo 4',
  DEFAULT_PHOTO_4_CAPTION: 'Default Photo 4 Caption',
  DEFAULT_PHOTO_5: 'Default Photo 5',
  DEFAULT_PHOTO_5_CAPTION: 'Default Photo 5 Caption',
  DEFAULT_PHOTO_6: 'Default Photo 6',
  DEFAULT_PHOTO_6_CAPTION: 'Default Photo 6 Caption',
  DEFAULT_PHOTO_7: 'Default Photo 7',
  DEFAULT_PHOTO_7_CAPTION: 'Default Photo 7 Caption',
  DEFAULT_PHOTO_8: 'Default Photo 8',
  DEFAULT_PHOTO_8_CAPTION: 'Default Photo 8 Caption',
  DEFAULT_PHOTO_9: 'Default Photo 9',
  DEFAULT_PHOTO_9_CAPTION: 'Default Photo 9 Caption',
  DEFAULT_PHOTO_10: 'Default Photo 10',
  DEFAULT_PHOTO_10_CAPTION: 'Default Photo 10 Caption',
  LAST_MODIFIED: 'Last Modified',
} as const;

export const REQUIRED_HEADERS = [
  SPECTORA_COLUMNS.SECTION_NAME,
  SPECTORA_COLUMNS.ITEM_NAME,
];
